In [2]:
import numpy
from torch.utils.data import DataLoader
from torch.utils.data import Dataset

In [3]:
import os
import numpy
import torch

In [4]:
data_dir = 'E:\\1D-Data'
label_dir = 'data_test'
DIR = os.path.join(data_dir,label_dir)
folder = os.listdir(DIR)

In [5]:
folder[0]

'00521.txt'

In [6]:
my_data = numpy.loadtxt(os.path.join(DIR,folder[0]))

In [7]:
class MyData(Dataset):

    def __init__(self, root_dir, label_dir):
        self.root_dir = root_dir
        self.label_dir = label_dir
        self.path = os.path.join(self.root_dir, self.label_dir)
        self.data_path = os.listdir(self.path)

    def __getitem__(self, idx):
        txt_name = self.data_path[idx]
        data_item_path = os.path.join(self.root_dir, self.label_dir, txt_name)
        data = numpy.loadtxt(data_item_path)
        label = self.label_dir
        return data, label

    def __len__(self):
        return len(self.data_path)

In [8]:
data_dir = 'E:\\1D-Data'
label_dir = 'data_test'
bus_data = MyData(data_dir,label_dir)

In [9]:
bus_data

In [10]:
len(bus_data)

3

In [11]:
#bus_data[1]

In [12]:
dataloader  = torch.utils.data.DataLoader(dataset = bus_data,
                  batch_size = 3,
                  shuffle =True)

In [15]:
for data in dataloader:
    data_1,label = data
    print('-----\n',data_1.shape)
    print(data_1.size)
    print(data_1)
    print(len(data_1))
    print(label)

-----
 torch.Size([3, 256])
<built-in method size of Tensor object at 0x000001DD4FC53BD0>
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0689, 0.1062, 0.0556, 0.0699, 0.1620, 0.1429, 0.0968, 0.2136,
         0.2528, 0.2156, 0.0621, 0.0921, 0.0685, 0.1390, 0.1187, 0.0952, 0.1089,
         0.0588, 0.0963, 0.2303, 0.2060, 0.1656, 0.4313, 0.3025, 0.1206, 0.1557,
         0.2430, 0.4075, 0.2715, 0.2091, 0.2643, 0.1178, 0.2080, 0.1378, 0.2851,
         0.2290, 0.1185, 0.1377, 0.2594, 0.2358, 0.2714, 0.1548, 0.0811, 0.0548,
         0.1594, 0.1865, 0.1644, 0.2760, 0.1200, 0.1426, 0.1011, 0.1894, 0.1887,
         0.1051, 0.0649, 0.1608, 0.0354, 0.1578, 0.0677, 0.0653, 0.1112, 0.2643,
         0.2967, 0.1434, 0.0803, 0.1018, 0.1563, 0.1443, 0.0412, 0.1275, 0.2387,
         0.1875, 0.0871, 0.1102, 0.2528, 0.2378, 0.1597, 0.0957, 0.1905, 0.1767,
         0.1638, 0.2376, 0.2298, 0.2278, 0.2405, 0.1577, 0.0301, 0.1530, 0.0399,
         0.1900, 0.

In [18]:
new_list = []
for i in range(3):
    print(data_1[i].size())
    #print(data_1[i])
    b = data_1[i].numpy()
    b=[b.tolist()]
    new_list.append(b)
    #b =torch.Tensor(b)
    #print(b)

new_list =torch.Tensor(new_list)
print(new_list)

torch.Size([256])
torch.Size([256])
torch.Size([256])
tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0689, 0.1062, 0.0556, 0.0699, 0.1620, 0.1429,
          0.0968, 0.2136, 0.2528, 0.2156, 0.0621, 0.0921, 0.0685, 0.1390,
          0.1187, 0.0952, 0.1089, 0.0588, 0.0963, 0.2303, 0.2060, 0.1656,
          0.4313, 0.3025, 0.1206, 0.1557, 0.2430, 0.4075, 0.2715, 0.2091,
          0.2643, 0.1178, 0.2080, 0.1378, 0.2851, 0.2290, 0.1185, 0.1377,
          0.2594, 0.2358, 0.2714, 0.1548, 0.0811, 0.0548, 0.1594, 0.1865,
          0.1644, 0.2760, 0.1200, 0.1426, 0.1011, 0.1894, 0.1887, 0.1051,
          0.0649, 0.1608, 0.0354, 0.1578, 0.0677, 0.0653, 0.1112, 0.2643,
          0.2967, 0.1434, 0.0803, 0.1018, 0.1563, 0.1443, 0.0412, 0.1275,
          0.2387, 0.1875, 0.0871, 0.1102, 0.2528, 0.2378, 0.1597, 0.0957,
          0.1905, 0.1767, 0.1638, 0.2376, 0.2298, 0.2278, 0.2405, 0.1577,
          0.0301, 0.1530, 0.0399, 0.1900, 0.3392, 0.3654, 

In [70]:
for i in range(1):
    print(data_1[i].size())
    print(data_1[i])
    data_1[i] = data_1[i].numpy()
    data_1[i]=[data_1[i].tolist()]
    
    data_1[i] =torch.Tensor(data_1[i])
    print(data_1[i])

torch.Size([256])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0699, 0.1360, 0.0364, 0.1421, 0.0796, 0.0550, 0.0555, 0.0962,
        0.0368, 0.1009, 0.1644, 0.1136, 0.1221, 0.1388, 0.2032, 0.0596, 0.0812,
        0.0232, 0.1333, 0.1099, 0.0487, 0.1798, 0.2599, 0.0764, 0.0670, 0.0418,
        0.0890, 0.0592, 0.0787, 0.1487, 0.1555, 0.0626, 0.3442, 0.2407, 0.1056,
        0.0208, 0.1235, 0.0496, 0.0969, 0.1414, 0.1051, 0.1523, 0.0874, 0.1060,
        0.0653, 0.0714, 0.1716, 0.2788, 0.2282, 0.1125, 0.0502, 0.2169, 0.1874,
        0.0969, 0.2212, 0.2473, 0.3043, 0.1515, 0.0522, 0.0906, 0.0445, 0.0642,
        0.1142, 0.0738, 0.1707, 0.3315, 0.1382, 0.1952, 0.3814, 0.2953, 0.1823,
        0.1729, 0.1444, 0.1227, 0.0245, 0.0956, 0.1334, 0.1006, 0.1016, 0.0764,
        0.1892, 0.2143, 0.1581, 0.1565, 0.2223, 0.2544, 0.1682, 0.1880, 0.1683,
        0.0657, 0.1506, 0.1257, 0.0679, 0.1474, 0.2177, 0.0516, 0.1082, 0.0882,
        0.1284, 0.1282

TypeError: can't assign a numpy.ndarray to a torch.DoubleTensor

In [ ]:
tensor([0, 1, 0, 0])

In [38]:
targets = ('0', '2', '0', '0')
print(targets[0])
#list=[0 for x in range(0,4)]
list = []
for i in range(4):
    list.append(int(targets[i]))
print(list)
list = torch.LongTensor(list)   
print(list)

0
[0, 2, 0, 0]
tensor([0., 2., 0., 0.])


In [ ]:
if targets[i] == 0:
        list[i] = 0
    elif targets[i] == 1:
        list[i] = 1
    else:
        list[i] = 2